config/routes.rb
Rails.application.routes.draw do
  root 'airports#index'
  resources :flights
  #resources:flights
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :flights, foreign_key: "departure_airport_id"
  has_many :flights, foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airport, foreign_key: "departure_airport_id"
  belongs_to :airport, foreign_key: "arrival_airport_id"
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def index
    @airports = Airport.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @flights = Flight.all
  end

  def new
    @flights = Flight.all
    @flight = Flight.new
  end

  def create
    @flights = Flight.all
    @flight = Flight.new(params[:flight])
    if @flight.save!
      redirect_to @flight
    else
      render 'new'
    end
  end

  #pour montrer un vol en particulier .... faire la vue ...
  def show
     @flight = Flight.find(params[:id])
  end

end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/airports/index.html.erb
<select name="airports_id">
   <%= @airports.each do |airport| %>
     <option value="<%= airport.id %>">Aéoroport de <%= airport.airport_code %></option>
   <% end %>
 </select>

app/views/flights/index.html.erb
<h1>Flights List</h1>

<table class="table table-dark">
  <thead>

    <tr>
      <th scope="col">#</th>
      <th scope="col">Departure</th>
      <th scope="col">Destination</th>
      <th scope="col">Date</th>
      <th scope="col">Passenger number</th>
    </tr>
  </thead>

  <tbody>
    <% i = 1 %>
    <% @flights.each do |flight| %>
    <tr>
      <th scope="row"><%= i %></th>
      <td><%=Airport.find(flight.departure_airport_id).airport_code%></td>
      <td><%=Airport.find(flight.arrival_airport_id).airport_code%></td>
      <td><%=flight.departure_date%></td>
      <td><center><%=rand(0..150)%></center></td>
      <td><%= link_to 'Show the comment', flights_path(flight)%></td>
      <% i = i + 1%>
    </tr>

  </tbody>
  <%end%>

</table>

app/views/flights/new.html.erb
<%= form_tag flights_path, method: :post do %>

<%= select_tag :departure_airport_id, options_for_select(@flights.collect { |flight| [Airport.find(flight.departure_airport_id).airport_code, flight.departure_airport_id] } )%>


<%= submit_tag "Go !"%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Air Hacking Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>